### ISSUE TITLE
Vendored framework CoreBitcoin missing source files

### ISSUE THREAD

**Issue by wjmelements** [uport-project/UPTEthereumSigner#1]
There are headers but no source files so it can't link.

**Comment by wjmelements** [comment]
It seems the included framework has the binaries, so this may have been an issue with my BUCK configuration.

**Comment by wjmelements** [comment]
I figured it out; the vendored framework is missing x86-64, which is required to run the emulator.

**Comment by joshuabell** [comment]
This project uses the secure enclave which is not supported on the simulator.
I've updated the readme with instructions to run on a device.
