### ISSUE TITLE
cocoapods 404

### ISSUE THREAD

**Issue by wjmelements** [uport-project/UPTEthereumSigner#2]
http://cocoapods.org/pods/UPTEthereumSigner is a 404

**Comment by wjmelements** [comment]
This causes

```
[!] Unable to find a specification for `UPTEthereumSigner`
```

which breaks your usage instructions.

**Comment by wjmelements** [comment]
The minimum fix here is to update the readme so that it no longer claims to work with cocoapods.

**Comment by joshuabell** [comment]
I updated the readme with instructions to use submodules.
